# @api = https://app-fashion-like.herokuapp.com/v1-api-post
@api = http://localhost:3001/v1-api-post
@token = 


### todos los post
GET  {{api}}
x-access-token : {{token}}

### crear un post
POST  {{api}}
x-access-token : {{token}}
content-type: application/json

{
    "post": "post6",
    "img":"./imagenes/post6.jpg",
    "voto":"like"
}

### eliminar un post
DELETE  {{api}}/c84545c4-a19e-4f8f-94c5-28d5fd445d2e
x-access-token : {{token}}
content-type: application/json
