# @api = https://app-fashion-like.herokuapp.com/v1-api-register
@api = http://localhost:3001/v1-api-register
@token = 


### crear un usuario
POST  {{api}}
content-type: application/json

{
    "name": "alfredo",
    "lastname":"lopez",
    "email":"alfredo@mail.com",
    "password":"123mnxA?g"
}